const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtDate=v=>v?new Date(v).toLocaleDateString('en-AU',{day:'2-digit',month:'short',year:'numeric'}):'—';
const fmtTime=v=>v?new Date(v).toLocaleString('en-AU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const pct=(n,d)=>d?Math.round(Number(n||0)*100/Number(d)):0;
const app=$('#app');
const state={user:null,view:'dashboard',projectId:'',projects:[],systems:[],equipment:[],templates:[],inspections:[],defects:[],points:[],turnover:[],witness:[],dashboard:{},users:[],query:'',filters:{}};

const API_CACHE='qx-api-cache:'; const QUEUE_KEY='qx-offline-queue-v2';
function getQueue(){try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]')}catch{return[]}}
function setQueue(q){localStorage.setItem(QUEUE_KEY,JSON.stringify(q))}
async function api(path,options={}){const method=(options.method||'GET').toUpperCase();const headers={...(options.body&&!(options.body instanceof Blob)?{'content-type':'application/json'}:{}),...(options.headers||{})};let r;try{r=await fetch(path,{credentials:'same-origin',headers,...options})}catch(err){if(method==='GET'){try{const hit=JSON.parse(localStorage.getItem(API_CACHE+path)||'null');if(hit?.data)return hit.data}catch{}throw err}const queueable=['POST','PATCH','DELETE'].includes(method)&&typeof options.body==='string'&&!path.startsWith('/api/auth/')&&!path.startsWith('/api/setup/');if(queueable&&!navigator.onLine){const q=getQueue();q.push({id:crypto.randomUUID(),path,method,body:options.body,headers,queued_at:new Date().toISOString()});setQueue(q);updateQueueBadge();return {queued:true,offline:true}}throw err}let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||`Request failed (${r.status})`);if(method==='GET'&&d)localStorage.setItem(API_CACHE+path,JSON.stringify({at:Date.now(),data:d}));return d}
async function flushQueue(){if(!navigator.onLine)return;const q=getQueue();if(!q.length)return;const remaining=[];for(const item of q){try{const r=await fetch(item.path,{method:item.method,body:item.body,credentials:'same-origin',headers:item.headers});if(!r.ok)remaining.push(item)}catch{remaining.push(item)}}setQueue(remaining);updateQueueBadge();if(q.length!==remaining.length){toast(`${q.length-remaining.length} offline update${q.length-remaining.length===1?'':'s'} synchronised`);try{await loadAll();render()}catch{}}}
function updateQueueBadge(){const el=$('#networkState');if(!el)return;const n=getQueue().length;if(!navigator.onLine){el.textContent=`● OFFLINE${n?` • ${n} queued`:''}`;el.classList.add('off')}else{el.textContent=n?`● LIVE • ${n} syncing`:'● LIVE';el.classList.remove('off')}}
function toast(msg){document.body.insertAdjacentHTML('beforeend',`<div class="toast">${esc(msg)}</div>`);setTimeout(()=>$('.toast')?.remove(),2200)}
function pill(v){const s=String(v||'not_started').replaceAll('_',' ');return `<span class="pill ${esc(String(v||''))}">${esc(s)}</span>`}
function progress(v){const n=Math.max(0,Math.min(100,Number(v||0)));return `<div class="readiness"><div class="progress"><i style="width:${n}%"></i></div><b>${n}%</b></div>`}
function currentProject(){return state.projects.find(p=>p.id===state.projectId)||null}
function projectName(id){const p=state.projects.find(x=>x.id===id);return p?`${p.code} — ${p.name}`:'—'}
function filtered(rows){if(!state.projectId)return rows;return rows.filter(x=>x.project_id===state.projectId)}

function navBtn(id,icon,label){return `<button class="navbtn ${state.view===id?'active':''}" data-view="${id}"><span class="navicon">${icon}</span>${label}</button>`}
function shell(content){const u=state.user||{};return `<div class="layout"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brandmark">QX</div><div><b>Elliot Qx</b><small>Commissioning OS</small></div></div><div class="navlabel">Control</div>${navBtn('dashboard','◈','Command Centre')}${navBtn('projects','▦','Projects')}${navBtn('systems','⌘','Systems & Readiness')}${navBtn('intelligence','◆','Qx Intelligence')}<div class="navlabel">Field Execution</div>${navBtn('equipment','◇','Equipment')}${navBtn('inspections','✓','QA & Commissioning')}${navBtn('points','↯','BMS I/O Checkout')}${navBtn('defects','!','Defects / Punch')}<div class="navlabel">Completion</div>${navBtn('witness','◎','Witness & Hold Points')}${navBtn('turnover','▣','Turnover Packages')}${navBtn('templates','≡','Template Library')}<div class="sidefoot"><div class="userline"><div class="avatar">${esc((u.name||'U')[0])}</div><div><b>${esc(u.name||'User')}</b><small>${esc(u.role||'')}</small></div></div><button class="navbtn" id="logout" style="margin-top:8px"><span class="navicon">↪</span>Sign out</button></div></aside><main class="main"><header class="topbar"><button class="btn btn-small mobile-menu" id="menuBtn">☰</button><select class="project-picker" id="projectPicker"><option value="">All projects / portfolio</option>${state.projects.map(p=>`<option value="${p.id}" ${p.id===state.projectId?'selected':''}>${esc(p.code)} — ${esc(p.name)}</option>`).join('')}</select><span class="online ${navigator.onLine?'':'off'}" id="networkState">${navigator.onLine?'● LIVE':'● OFFLINE'}</span></header><section class="content">${content}</section></main></div>`}
function hero(title,sub,actions=''){return `<div class="hero"><div><div class="eyebrow">${esc(currentProject()?.code||'ELLIOT CONTROLS')}</div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><div class="actions">${actions}</div></div>`}
function card(label,value,sub='',tone=''){return `<div class="card kpi"><div class="label">${label}</div><div class="metric ${tone}">${value}</div><div class="sub">${sub}</div></div>`}

function renderLogin(initialized=true){app.innerHTML=`<div class="auth"><div class="auth-card"><div class="brandmark">QX</div><h1>Elliot Qx</h1><p>${initialized?'QA, commissioning, systems completion and turnover — one source of truth from install to handover.':'Create the first secure administrator account.'}</p><form id="authForm">${!initialized?`<div class="field"><label>Bootstrap token</label><input name="token" type="password" required></div><div class="field"><label>Your name</label><input name="name" required></div>`:''}<div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" minlength="12" required></div><button class="btn btn-primary" style="width:100%">${initialized?'Sign in':'Create administrator'}</button></form><div id="authError"></div></div></div>`;$('#authForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{if(initialized){const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify(data)});state.user=r.user;await loadAll();render()}else{const r=await api('/api/setup/bootstrap',{method:'POST',body:JSON.stringify(data)});state.user=r.user;await loadAll();render()}}catch(err){$('#authError').innerHTML=`<div class="error" style="margin-top:12px">${esc(err.message)}</div>`}}}

async function loadAll(){const q=state.projectId?`?project_id=${encodeURIComponent(state.projectId)}`:'';const [p,t,d,s,e,i,df,pts,top,w,u]=await Promise.all([api('/api/projects'),api('/api/templates'),api(`/api/dashboard${q}`),api(`/api/systems${q}`),api(`/api/equipment${q}`),api(`/api/inspections${q}`),api(`/api/defects${q}`),api(`/api/bms-points${q}`),api(`/api/turnover${q}`),api(`/api/witness${q}`),api('/api/users')]);state.projects=p.projects;state.templates=t.templates;state.dashboard=d;state.systems=s.systems;state.equipment=e.equipment;state.inspections=i.inspections;state.defects=df.defects;state.points=pts.points;state.turnover=top.packages;state.witness=w.witness;state.users=u.users}
async function boot(){try{setQueue(getQueue().filter(x=>!String(x.path||'').startsWith('/api/auth/')&&!String(x.path||'').startsWith('/api/setup/')));if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const st=await api('/api/setup/status');if(!st.initialized)return renderLogin(false);const me=await api('/api/me');state.user=me.user;await loadAll();render()}catch(e){renderLogin(true)}}

function dashboardView(){const d=state.dashboard,eq=d.equipment||{},df=d.defects||{},ins=d.inspections||{},pts=d.points||{},top=d.turnover||{},wit=d.witness||{};const eqp=pct(eq.complete,eq.total),pointp=pct(pts.passed,pts.total),turn=Math.round(Number(top.avg_readiness||0));const p=currentProject();return `${hero(p?'Project Command Centre':'Portfolio Command Centre','Live readiness, blockers, field execution and handover position',`<button class="btn btn-primary" id="quickTest">+ Start field test</button><button class="btn" id="quickDefect">+ Defect</button>`)}<div class="banner"><div style="font-size:22px">⚡</div><div><strong>Commissioning Readiness Engine</strong><p>Qx measures actual readiness from equipment, test completion, BMS I/O, Category A punch items, witness points and turnover evidence — not just checklist percentages.</p></div></div><div class="cards">${card('Equipment complete',`${eqp}%`,`${eq.complete||0} / ${eq.total||0} assets`,'green')}${card('BMS I/O proven',`${pointp}%`,`${pts.failed||0} failed points`,pts.failed?'red':'blue')}${card('Open punch',df.open||0,`${df.cat_a||0} Category A`,df.cat_a?'red':'amber')}${card('Witness holds',ins.witness||wit.requested||0,'Awaiting witness / approval','amber')}${card('Turnover readiness',`${turn}%`,`${top.ready||0} packages ready`,turn>85?'green':'blue')}${card('Live projects',d.projects?.active||0,`${d.projects?.total||0} total`,'blue')}</div><div class="grid2"><div><div class="section-head"><h3>${p?'System readiness':'Project readiness'}</h3><span>What is gating completion</span></div>${p?systemReadinessTable():projectTable(state.projects.slice(0,12))}</div><div><div class="section-head"><h3>Recent field activity</h3><span>Audit trail</span></div><div class="card activity">${(d.recent||[]).slice(0,10).map(a=>`<div class="activity-item"><b>${esc(a.user_name||'System')}</b> ${esc(a.action.replaceAll('_',' '))} ${esc(a.entity_type)}<small>${fmtTime(a.created_at)}</small></div>`).join('')||'<div class="empty">No activity yet</div>'}</div></div></div>`}
function projectTable(rows){if(!rows.length)return '<div class="card empty">No projects yet.</div>';return `<div class="table-wrap"><table><thead><tr><th>Project</th><th>Status</th><th>Systems</th><th>Equipment</th><th>Cat A</th><th>Open punch</th><th>Turnover</th></tr></thead><tbody>${rows.map(p=>`<tr><td><strong>${esc(p.code)}</strong><br><span class="muted">${esc(p.name)}</span></td><td>${pill(p.status)}</td><td>${p.system_count||0}</td><td>${p.equipment_count||0}</td><td>${p.cat_a||0}</td><td>${p.open_defects||0}</td><td>${progress(p.turnover_readiness||0)}</td></tr>`).join('')}</tbody></table></div>`}
function systemReadinessTable(){if(!state.systems.length)return '<div class="card empty">Create systems to start systemised completion tracking.</div>';return `<div class="table-wrap"><table><thead><tr><th>System</th><th>Discipline</th><th>Status</th><th>Equipment</th><th>Open punch</th><th>Target</th></tr></thead><tbody>${state.systems.map(s=>`<tr><td><strong>${esc(s.code)}</strong><br><span class="muted">${esc(s.name)}</span></td><td>${esc(s.discipline)}</td><td>${pill(s.status)}</td><td>${s.equipment_count||0}</td><td>${s.open_defects||0}</td><td>${fmtDate(s.target_date)}</td></tr>`).join('')}</tbody></table></div>`}

async function refreshIntelligence(){if(!state.projectId)return;try{state.intelligence=await api(`/api/readiness?project_id=${encodeURIComponent(state.projectId)}&snapshot=1`);render()}catch(e){toast(e.message)}}
function intelligenceView(){if(!state.projectId)return `${hero('Qx Intelligence','Select a project to calculate real commissioning readiness')}<div class="card empty">Choose a project from the top bar. Qx will calculate blockers across QA, BMS I/O, punch, witness and turnover.</div>`;const r=state.intelligence; if(!r){setTimeout(refreshIntelligence,0);return `${hero('Qx Intelligence','Calculating project readiness and completion blockers')}<div class="card empty">Analysing live project data…</div>`}return `${hero('Qx Intelligence','The shortest path from today to energisation, witness and handover','<button class="btn btn-primary" id="refreshIntel">Recalculate readiness</button>')}<div class="intel-grid"><div class="card"><div class="section-head"><h3>Readiness score</h3><span>${esc(r.grade)}</span></div><div class="readiness-ring" style="--p:${r.score}"><strong>${r.score}%</strong></div><p class="muted" style="text-align:center;margin-top:14px">Weighted from live QA, Category A punch, BMS I/O, witness, turnover and asset completion.</p></div><div class="card"><div class="section-head"><h3>Completion blockers</h3><span>${r.blockers.length} active</span></div>${r.blockers.length?r.blockers.map(b=>`<div class="blocker"><span class="sev ${esc(b.severity)}"></span><div><b>${esc(b.label)}</b><small>${esc(b.code.replaceAll('_',' '))}</small></div></div>`).join(''):'<div class="empty">No blocking conditions detected. Validate required evidence and authorised sign-offs before handover.</div>'}</div></div><div class="section-head"><h3>Why Qx wins for Elliot</h3><span>Built around field delivery</span></div><div class="cards"><div class="switch-reason"><b>One completion graph</b><span class="muted">Equipment, QA, I/O, punch, witness and turnover use the same live project structure.</span></div><div class="switch-reason"><b>BMS-native</b><span class="muted">Bulk point lists and four-stage I/O proof are first-class workflows, not generic forms.</span></div><div class="switch-reason"><b>Automatic blockers</b><span class="muted">PMs see why a system cannot be handed over instead of interpreting dozens of reports.</span></div><div class="switch-reason"><b>Evidence at the asset</b><span class="muted">Photos, tests, defects and sign-off remain tied to the equipment and system.</span></div></div>`}

function projectsView(){return `${hero('Projects','Portfolio, commissioning ownership and completion dates','<button class="btn btn-primary" id="addProject">+ New project</button>')}${projectTable(state.projects)}`}
function systemsView(){return `${hero('Systems & Readiness','Systemise the job exactly how it will be commissioned and handed over','<button class="btn btn-primary" id="addSystem">+ Add system</button><button class="btn" id="addTurnover">+ Turnover package</button>')}${systemReadinessTable()}`}
function equipmentView(){const rows=state.equipment;return `${hero('Equipment Register','Every asset linked to QA, tests, punch, I/O and turnover','<button class="btn btn-primary" id="addEquipment">+ Add equipment</button>')}<div class="toolbar"><input class="search" id="searchBox" placeholder="Search tag, equipment, system, location…" value="${esc(state.query)}"><select class="mini-select" id="eqStatus"><option value="">All statuses</option><option>not_started</option><option>qa</option><option>commissioning</option><option>witness</option><option>blocked</option><option>complete</option></select></div>${equipmentTable(rows)}`}
function equipmentTable(rows){const q=state.query.toLowerCase(),st=state.filters.eqStatus||'';const list=rows.filter(e=>(!q||[e.tag,e.name,e.system,e.subsystem,e.building,e.level,e.area].join(' ').toLowerCase().includes(q))&&(!st||e.status===st));if(!list.length)return '<div class="card empty">No matching equipment.</div>';return `<div class="table-wrap"><table><thead><tr><th>Tag</th><th>Equipment</th><th>System</th><th>Location</th><th>Status</th><th>Approved tests</th><th>Punch</th><th>QR</th></tr></thead><tbody>${list.map(e=>`<tr><td><strong>${esc(e.tag)}</strong></td><td>${esc(e.name)}<br><span class="muted">${esc([e.manufacturer,e.model].filter(Boolean).join(' ')||e.equipment_type||'')}</span></td><td>${esc(e.system||'—')}<br><span class="muted">${esc(e.subsystem||'')}</span></td><td>${esc([e.building,e.level,e.area].filter(Boolean).join(' / ')||'—')}</td><td>${pill(e.status)}</td><td>${e.approved_tests||0}</td><td>${e.open_defects||0}</td><td><button class="btn btn-small" data-assetlink="${e.id}">Link</button></td></tr>`).join('')}</tbody></table></div>`}

function inspectionsView(){return `${hero('QA & Commissioning','Installation QA, ITPs, PFCs, FPTs and integrated testing','<button class="btn btn-primary" id="addInspection">+ Start test</button>')}<div class="toolbar"><input class="search" id="searchBox" placeholder="Search tests, asset tags, templates…" value="${esc(state.query)}"></div>${inspectionTable()}`}
function inspectionTable(){const q=state.query.toLowerCase(),list=state.inspections.filter(i=>!q||[i.title,i.equipment_tag,i.template_name,i.discipline].join(' ').toLowerCase().includes(q));if(!list.length)return '<div class="card empty">No QA or commissioning tests yet.</div>';return `<div class="table-wrap"><table><thead><tr><th>Test / Inspection</th><th>Asset</th><th>Stage</th><th>Progress</th><th>Fails</th><th>Status</th><th>Updated</th></tr></thead><tbody>${list.map(i=>`<tr data-inspection="${i.id}" style="cursor:pointer"><td><strong>${esc(i.title)}</strong><br><span class="muted">${esc(i.template_name)}</span></td><td>${esc(i.equipment_tag||'Project / system')}</td><td>${pill(i.stage)}</td><td>${progress(pct(i.answered,i.total_lines))}</td><td>${i.fails||0}</td><td>${pill(i.status)}</td><td>${fmtTime(i.updated_at)}</td></tr>`).join('')}</tbody></table></div>`}

function pointsView(){const points=state.points,q=state.query.toLowerCase(),list=points.filter(p=>!q||[p.controller,p.point_name,p.point_type,p.equipment_tag,p.io_address,p.cable_number].join(' ').toLowerCase().includes(q));const pass=list.filter(p=>p.overall_status==='pass').length,fail=list.filter(p=>p.overall_status==='fail').length;return `${hero('BMS I/O Checkout','Bulk point-to-point verification built for controls contractors','<button class="btn btn-primary" id="importPoints">⇧ Import CSV</button>')}<div class="cards" style="grid-template-columns:repeat(4,1fr)">${card('Points',list.length,'Current register','blue')}${card('Proven',pass,`${pct(pass,list.length)}% complete`,'green')}${card('Failed',fail,'Requires rectification',fail?'red':'')}${card('Untested',Math.max(0,list.length-pass-fail),'Field workload','amber')}</div><div class="toolbar"><input class="search" id="searchBox" placeholder="Search controller, point, address, cable…" value="${esc(state.query)}"></div>${list.length?`<div class="table-wrap"><table><thead><tr><th>Controller / Point</th><th>Type</th><th>Asset</th><th>Address</th><th>Field</th><th>Controller</th><th>Graphics</th><th>Alarm</th><th>Overall</th></tr></thead><tbody>${list.slice(0,1000).map(p=>`<tr data-point="${p.id}" style="cursor:pointer"><td><span class="muted">${esc(p.controller||'')}</span><br><strong>${esc(p.point_name)}</strong></td><td>${pill(p.point_type)}</td><td>${esc(p.equipment_tag||'—')}</td><td>${esc(p.io_address||'—')}</td><td>${pill(p.field_status)}</td><td>${pill(p.controller_status)}</td><td>${pill(p.graphics_status)}</td><td>${pill(p.alarm_status)}</td><td>${pill(p.overall_status)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="card empty">No BMS points yet. Import a CSV from your points list or I/O schedule.</div>'}`}

function defectsView(){const q=state.query.toLowerCase(),list=state.defects.filter(d=>!q||[d.title,d.description,d.equipment_tag,d.discipline,d.assigned_name].join(' ').toLowerCase().includes(q));const a=list.filter(d=>d.category==='A'&&!['closed','verified'].includes(d.status)).length;return `${hero('Defects & Punch','A/B/C completion punch with rectification evidence and verification','<button class="btn btn-primary" id="addDefect">+ Raise defect</button>')}<div class="cards" style="grid-template-columns:repeat(4,1fr)">${card('Category A',a,'Blocks energisation / turnover',a?'red':'green')}${card('Open',list.filter(d=>!['closed','verified'].includes(d.status)).length,'All active punch','amber')}${card('Rectified',list.filter(d=>d.status==='rectified').length,'Awaiting verification','blue')}${card('Closed',list.filter(d=>['closed','verified'].includes(d.status)).length,'Verified evidence','green')}</div><div class="toolbar"><input class="search" id="searchBox" placeholder="Search defect, asset, owner…" value="${esc(state.query)}"></div>${list.length?`<div class="table-wrap"><table><thead><tr><th>Cat</th><th>Defect</th><th>Asset</th><th>Discipline</th><th>Severity</th><th>Status</th><th>Owner</th><th>Due</th></tr></thead><tbody>${list.map(d=>`<tr data-defect="${d.id}" style="cursor:pointer"><td>${pill(d.category?.toLowerCase())}</td><td><strong>${esc(d.title)}</strong><br><span class="muted">${esc(d.description||'')}</span></td><td>${esc(d.equipment_tag||'—')}</td><td>${esc(d.discipline)}</td><td>${pill(d.severity)}</td><td>${pill(d.status)}</td><td>${esc(d.assigned_name||'Unassigned')}</td><td>${fmtDate(d.due_date)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="card empty">No defects.</div>'}`}

function witnessView(){return `${hero('Witness & Hold Points','Control client/consultant witness requests and approval gates','<button class="btn btn-primary" id="addWitness">+ Request witness</button>')}${state.witness.length?`<div class="table-wrap"><table><thead><tr><th>Requested</th><th>System</th><th>Test / Hold Point</th><th>Witness party</th><th>Status</th><th>Outcome</th></tr></thead><tbody>${state.witness.map(w=>`<tr><td><strong>${fmtDate(w.requested_for)}</strong></td><td>${esc(w.system_code||'—')}</td><td>${esc(w.inspection_title||'System witness')}</td><td>${esc(w.witness_party||'Client / consultant')}</td><td>${pill(w.status)}</td><td>${esc(w.outcome||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="card empty">No witness requests yet.</div>'}`}

function turnoverView(){const avg=state.turnover.length?Math.round(state.turnover.reduce((a,b)=>a+Number(b.readiness_percent||0),0)/state.turnover.length):0;return `${hero('Turnover Packages','Automatic closeout dossier readiness by system','<button class="btn btn-primary" id="addTurnover">+ New package</button>')}<div class="banner"><div style="font-size:22px">▣</div><div><strong>Handover without the end-of-job scramble</strong><p>Each package tracks as-builts, QA records, electrical tests, BMS I/O, functional tests, witness records, punch closure, O&M, backups and training evidence.</p></div></div><div class="cards" style="grid-template-columns:repeat(3,1fr)">${card('Portfolio readiness',`${avg}%`,'Across current packages',avg>85?'green':'blue')}${card('Ready packages',state.turnover.filter(x=>['ready','approved'].includes(x.status)).length,'Ready for acceptance','green')}${card('Incomplete',state.turnover.filter(x=>!['ready','approved'].includes(x.status)).length,'Outstanding dossier items','amber')}</div>${state.turnover.length?`<div class="grid3">${state.turnover.map(t=>`<div class="card" data-turnover="${t.id}" style="cursor:pointer"><div class="eyebrow">${esc(t.system_code||'PROJECT')}</div><h3 style="margin:7px 0 3px">${esc(t.name)}</h3><div class="muted" style="font-size:11px">${esc(t.system_name||'Project-wide package')}</div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:17px"><div class="score-ring" style="--p:${Number(t.readiness_percent||0)}"><b>${Number(t.readiness_percent||0)}%</b></div><div style="text-align:right">${pill(t.status)}<div class="muted" style="margin-top:8px;font-size:11px">${t.complete_items||0}/${t.required_items||0} required items</div></div></div></div>`).join('')}</div>`:'<div class="card empty">Create the first turnover package for a system.</div>'}`}

function templatesView(){return `${hero('Template Library','Reusable company standards for QA, pre-functional, functional and integrated testing')}<div class="grid3">${state.templates.map(t=>`<div class="card"><div class="eyebrow">${esc(t.discipline)} • ${esc(t.stage)}</div><h3 style="margin:7px 0">${esc(t.name)}</h3><p class="muted" style="font-size:12px;line-height:1.5;min-height:55px">${esc(t.description||'')}</p><div style="display:flex;justify-content:space-between;margin-top:12px"><span>${t.item_count} checks</span><span class="muted">${t.hold_points} hold points</span></div></div>`).join('')}</div>`}

function modal(title,body,wide=false){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal ${wide?'wide':''}"><div class="modal-head"><div><div class="eyebrow">ELLIOT QX</div><h2>${esc(title)}</h2></div><button class="btn btn-small" id="closeModal">Close</button></div>${body}</div></div>`);$('#closeModal').onclick=()=>$('#modal').remove()}
function projectOptions(){return state.projects.map(p=>`<option value="${p.id}" ${p.id===state.projectId?'selected':''}>${esc(p.code)} — ${esc(p.name)}</option>`).join('')}
function systemOptions(){return state.systems.map(s=>`<option value="${s.id}">${esc(s.code)} — ${esc(s.name)}</option>`).join('')}
function equipmentOptions(){return state.equipment.map(e=>`<option value="${e.id}">${esc(e.tag)} — ${esc(e.name)}</option>`).join('')}
function userOptions(){return state.users.map(u=>`<option value="${u.id}">${esc(u.name)} — ${esc(u.role)}</option>`).join('')}

function wireActions(){
  $('#projectPicker').onchange=async e=>{state.projectId=e.target.value;state.query='';await loadAll();render()};
  $('#menuBtn')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
  $$('.navbtn[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.query='';$('#sidebar').classList.remove('open');render()});
  $('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'}).catch(()=>{});state.user=null;renderLogin(true)};
  $('#searchBox')?.addEventListener('input',e=>{state.query=e.target.value;renderKeepFocus()});
  $('#eqStatus')?.addEventListener('change',e=>{state.filters.eqStatus=e.target.value;render()});
  $('#addProject')?.addEventListener('click',openProjectForm); $('#addSystem')?.addEventListener('click',openSystemForm); $('#addEquipment')?.addEventListener('click',openEquipmentForm); $('#addInspection')?.addEventListener('click',openInspectionForm); $('#quickTest')?.addEventListener('click',openInspectionForm); $('#addDefect')?.addEventListener('click',openDefectForm); $('#quickDefect')?.addEventListener('click',openDefectForm); $('#importPoints')?.addEventListener('click',openPointImport); $('#addTurnover')?.addEventListener('click',openTurnoverForm); $('#addWitness')?.addEventListener('click',openWitnessForm);
  $$('[data-inspection]').forEach(r=>r.onclick=()=>openInspection(r.dataset.inspection)); $$('[data-point]').forEach(r=>r.onclick=()=>openPoint(r.dataset.point)); $$('[data-defect]').forEach(r=>r.onclick=()=>openDefect(r.dataset.defect)); $$('[data-turnover]').forEach(r=>r.onclick=()=>openTurnover(r.dataset.turnover)); $$('[data-assetlink]').forEach(b=>b.onclick=()=>{const url=`${location.origin}/?asset=${b.dataset.assetlink}`;navigator.clipboard?.writeText(url);toast('Asset link copied')});
}
function renderKeepFocus(){const pos=$('#searchBox')?.selectionStart;render();const box=$('#searchBox');if(box){box.focus();box.setSelectionRange(pos,pos)}}
function render(){const views={dashboard:dashboardView,projects:projectsView,systems:systemsView,intelligence:intelligenceView,equipment:equipmentView,inspections:inspectionsView,points:pointsView,defects:defectsView,witness:witnessView,turnover:turnoverView,templates:templatesView};app.innerHTML=shell((views[state.view]||dashboardView)());wireActions();updateQueueBadge()}

function formSubmit(form,path,after){form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));try{await api(path,{method:'POST',body:JSON.stringify(data)});$('#modal')?.remove();await loadAll();render();toast(after||'Saved')}catch(err){form.insertAdjacentHTML('afterbegin',`<div class="error">${esc(err.message)}</div>`)}}}
function openProjectForm(){modal('Create project',`<form id="f"><div class="formgrid"><div class="field"><label>Project code</label><input name="code" required placeholder="MEL06"></div><div class="field"><label>Project name</label><input name="name" required></div><div class="field"><label>Client</label><input name="client"></div><div class="field"><label>Project type</label><select name="project_type"><option>data_centre</option><option selected>commercial</option><option>healthcare</option><option>infrastructure</option><option>industrial</option></select></div><div class="field"><label>Commissioning manager</label><input name="commissioning_manager"></div><div class="field"><label>Practical completion</label><input name="practical_completion" type="date"></div><div class="field span2"><label>Site address</label><input name="site_address"></div></div><button class="btn btn-primary">Create project</button></form>`);formSubmit($('#f'),'/api/projects','Project created')}
function openSystemForm(){modal('Add commissioning system',`<form id="f"><div class="formgrid"><div class="field"><label>Project</label><select name="project_id" required>${projectOptions()}</select></div><div class="field"><label>System code</label><input name="code" required placeholder="SYS-BMS-01"></div><div class="field"><label>System name</label><input name="name" required placeholder="BMS Controls Network"></div><div class="field"><label>Discipline</label><select name="discipline"><option>BMS</option><option>Electrical</option><option>Mechanical</option><option>Fire</option><option>Integrated Systems</option></select></div><div class="field"><label>Location / area</label><input name="location"></div><div class="field"><label>Target ready date</label><input name="target_date" type="date"></div></div><button class="btn btn-primary">Add system</button></form>`);formSubmit($('#f'),'/api/systems','System added')}
function openEquipmentForm(){modal('Add equipment',`<form id="f"><div class="formgrid"><div class="field"><label>Project</label><select name="project_id" required>${projectOptions()}</select></div><div class="field"><label>Tag</label><input name="tag" required placeholder="AHU-L03-01"></div><div class="field span2"><label>Description</label><input name="name" required placeholder="Level 3 Air Handling Unit 01"></div><div class="field"><label>System</label><input name="system" placeholder="AHU System"></div><div class="field"><label>Subsystem</label><input name="subsystem" placeholder="Level 3"></div><div class="field"><label>Building</label><input name="building"></div><div class="field"><label>Level</label><input name="level"></div><div class="field"><label>Area</label><input name="area"></div><div class="field"><label>Equipment type</label><input name="equipment_type" placeholder="AHU"></div><div class="field"><label>Manufacturer</label><input name="manufacturer"></div><div class="field"><label>Model</label><input name="model"></div></div><button class="btn btn-primary">Add equipment</button></form>`);formSubmit($('#f'),'/api/equipment','Equipment added')}
function openInspectionForm(){if(!state.projects.length)return toast('Create a project first');modal('Start QA / commissioning test',`<form id="f"><div class="formgrid"><div class="field"><label>Project</label><select name="project_id" required>${projectOptions()}</select></div><div class="field"><label>Equipment</label><select name="equipment_id"><option value="">Project / system wide</option>${equipmentOptions()}</select></div><div class="field span2"><label>Template</label><select name="template_id" required>${state.templates.map(t=>`<option value="${t.id}">${esc(t.discipline)} — ${esc(t.name)}</option>`).join('')}</select></div><div class="field span2"><label>Test title</label><input name="title" required placeholder="AHU-L03-01 Functional Performance Test"></div><div class="field"><label>Assign to</label><select name="assigned_to"><option value="">Unassigned</option>${userOptions()}</select></div></div><button class="btn btn-primary">Start field test</button></form>`);formSubmit($('#f'),'/api/inspections','Test created')}
function openDefectForm(){if(!state.projects.length)return toast('Create a project first');modal('Raise defect / punch item',`<form id="f"><div class="formgrid"><div class="field"><label>Project</label><select name="project_id" required>${projectOptions()}</select></div><div class="field"><label>Equipment</label><select name="equipment_id"><option value="">Project / system wide</option>${equipmentOptions()}</select></div><div class="field span2"><label>Defect title</label><input name="title" required></div><div class="field span2"><label>Description / required action</label><textarea name="description"></textarea></div><div class="field"><label>Category</label><select name="category"><option value="A">A — blocks energisation / turnover</option><option value="B" selected>B — must close before final handover</option><option value="C">C — minor / cosmetic</option></select></div><div class="field"><label>Severity</label><select name="severity"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></div><div class="field"><label>Discipline</label><select name="discipline"><option>BMS</option><option>Electrical</option><option>Mechanical</option><option>Switchboards</option><option>Fire</option><option>General</option></select></div><div class="field"><label>Assign to</label><select name="assigned_to"><option value="">Unassigned</option>${userOptions()}</select></div><div class="field"><label>Due date</label><input name="due_date" type="date"></div></div><button class="btn btn-primary">Raise defect</button></form>`);formSubmit($('#f'),'/api/defects','Defect raised')}
function openTurnoverForm(){if(!state.projects.length)return toast('Create a project first');modal('Create turnover package',`<form id="f"><div class="field"><label>Project</label><select name="project_id" required>${projectOptions()}</select></div><div class="field"><label>System</label><select name="system_id"><option value="">Project-wide</option>${systemOptions()}</select></div><div class="field"><label>Package name</label><input name="name" required placeholder="BMS System Completion Package"></div><button class="btn btn-primary">Create package with Qx readiness gates</button></form>`);formSubmit($('#f'),'/api/turnover','Turnover package created')}
function openWitnessForm(){modal('Request witness / hold point',`<form id="f"><div class="field"><label>Project</label><select name="project_id" required>${projectOptions()}</select></div><div class="field"><label>System</label><select name="system_id"><option value="">Project-wide</option>${systemOptions()}</select></div><div class="field"><label>Inspection / test</label><select name="inspection_id"><option value="">System witness</option>${state.inspections.map(i=>`<option value="${i.id}">${esc(i.title)}</option>`).join('')}</select></div><div class="field"><label>Requested date & time</label><input name="requested_for" type="datetime-local" required></div><div class="field"><label>Witness party</label><input name="witness_party" placeholder="Client / CxA / consultant"></div><button class="btn btn-primary">Request witness</button></form>`);formSubmit($('#f'),'/api/witness','Witness requested')}

async function openInspection(iid){try{const d=await api(`/api/inspections/${iid}`);const i=d.inspection;modal(i.title,`<div class="banner"><div>✓</div><div><strong>${esc(i.template_name)}</strong><p>${esc(i.equipment_tag||'Project/system test')} • ${esc(i.discipline)} • ${esc(i.stage)}</p></div></div><div id="results">${d.results.map(r=>`<div class="result-row"><div class="meta"><span>${esc(r.section)}</span>${r.hold_point?'<span class="pill witness_required">HOLD POINT</span>':''}</div><h4>${esc(r.item_text)}</h4><div class="result-buttons" data-result-id="${r.id}"><button class="btn btn-small ${r.result==='pass'?'selected pass':''}" data-value="pass">PASS</button><button class="btn btn-small ${r.result==='fail'?'selected fail':''}" data-value="fail">FAIL</button><button class="btn btn-small ${r.result==='na'?'selected na':''}" data-value="na">N/A</button></div></div>`).join('')}</div>`,true);$$('[data-result-id] button').forEach(b=>b.onclick=async()=>{const row=b.closest('[data-result-id]');try{const r=await api(`/api/inspection-results/${row.dataset.resultId}`,{method:'PATCH',body:JSON.stringify({result:b.dataset.value})});row.querySelectorAll('button').forEach(x=>x.className='btn btn-small');b.classList.add('selected',b.dataset.value);toast(b.dataset.value==='fail'?'Failed check — Category A punch auto-created':`Result saved • ${r.status.replaceAll('_',' ')}`);await loadAll()}catch(err){toast(err.message)}})}catch(err){toast(err.message)}}

async function openPoint(pid){const p=state.points.find(x=>x.id===pid);if(!p)return;modal(`I/O Checkout — ${p.point_name}`,`<div class="banner"><div>↯</div><div><strong>${esc(p.controller||'Controller')} • ${esc(p.point_type)}</strong><p>${esc([p.io_address,p.cable_number,p.terminal].filter(Boolean).join(' • ')||'Field point')}</p></div></div><form id="pf"><div class="formgrid"><div class="field"><label>Field device</label><select name="field_status">${statusOpts(p.field_status)}</select></div><div class="field"><label>Controller I/O</label><select name="controller_status">${statusOpts(p.controller_status)}</select></div><div class="field"><label>Graphics / HMI</label><select name="graphics_status">${statusOpts(p.graphics_status)}</select></div><div class="field"><label>Alarm / sequence</label><select name="alarm_status">${statusOpts(p.alarm_status)}</select></div><div class="field span2"><label>Comment</label><textarea name="comment">${esc(p.comment||'')}</textarea></div></div><button class="btn btn-primary">Save point test</button></form>`);$('#pf').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api(`/api/bms-points/${pid}`,{method:'PATCH',body:JSON.stringify(data)});$('#modal').remove();await loadAll();render();toast('I/O point updated')}catch(err){toast(err.message)}}}
function statusOpts(v){return ['not_tested','pass','fail','na'].map(x=>`<option value="${x}" ${x===v?'selected':''}>${x.replaceAll('_',' ')}</option>`).join('')}

function openPointImport(){if(!currentProject()&&!state.projectId)return toast('Select a project before importing points');modal('Import BMS I/O points from CSV',`<div class="banner"><div>⇧</div><div><strong>Fast point-list ingestion</strong><p>Paste CSV exported from Excel/Simpro/design schedules. Required columns: point_name, point_type. Optional: controller, io_address, cable_number, terminal, field_device, engineering_units, normal_state.</p></div></div><div class="field"><label>CSV data</label><textarea id="csv" style="min-height:260px" placeholder="controller,point_name,point_type,io_address,cable_number,terminal\nJACE-01,AHU-01 Supply Air Temp,AI,UI1,BMS-001,X1:1\nJACE-01,AHU-01 Fan Enable,DO,UO1,BMS-002,X1:2"></textarea></div><button class="btn btn-primary" id="doImport">Import points</button>`,true);$('#doImport').onclick=async()=>{try{const rows=parseCSV($('#csv').value);if(!rows.length)throw new Error('No valid CSV rows found');const r=await api('/api/bms-points/import',{method:'POST',body:JSON.stringify({project_id:state.projectId,points:rows})});$('#modal').remove();await loadAll();render();toast(`${r.created} points imported`)}catch(err){toast(err.message)}}}
function parseCSV(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const split=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out};const headers=split(lines[0]).map(x=>x.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''));return lines.slice(1).map(line=>{const vals=split(line),o={};headers.forEach((h,i)=>o[h]=vals[i]||'');return o}).filter(x=>x.point_name&&x.point_type)}

async function openDefect(did){const d=state.defects.find(x=>x.id===did);if(!d)return;modal(`Punch ${d.category} — ${d.title}`,`<div class="banner"><div>!</div><div><strong>${esc(d.equipment_tag||'Project / system')}</strong><p>${esc(d.description||'No description')}</p></div></div><div class="formgrid"><div class="card"><div class="eyebrow">Status</div><div style="margin-top:8px">${pill(d.status)}</div></div><div class="card"><div class="eyebrow">Owner</div><div style="margin-top:8px">${esc(d.assigned_name||'Unassigned')}</div></div></div><form id="df" style="margin-top:12px"><div class="field"><label>Update status</label><select name="status"><option value="open">Open</option><option value="assigned">Assigned</option><option value="rectified">Rectified — ready to verify</option><option value="verified">Verified</option><option value="closed">Closed</option></select></div><div class="field"><label>Rectification / verification note</label><textarea name="rectification_note">${esc(d.rectification_note||'')}</textarea></div><button class="btn btn-primary">Update punch item</button></form>`);$('#df').onsubmit=async e=>{e.preventDefault();try{await api(`/api/defects/${did}`,{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#modal').remove();await loadAll();render();toast('Punch item updated')}catch(err){toast(err.message)}}}

async function openTurnover(tid){try{const d=await api(`/api/turnover/${tid}`);modal(d.package.name,`<div class="banner"><div>▣</div><div><strong>${Number(d.package.readiness_percent||0)}% ready for handover</strong><p>${esc(d.package.system_code||'Project-wide')} • ${d.package.complete_items||0}/${d.package.required_items||0} required items complete</p></div></div><div class="table-wrap"><table><thead><tr><th>Category</th><th>Required evidence / gate</th><th>Status</th></tr></thead><tbody>${d.items.map(x=>`<tr><td>${esc(x.category)}</td><td><strong>${esc(x.name)}</strong>${x.note?`<br><span class="muted">${esc(x.note)}</span>`:''}</td><td><select class="mini-select" data-toi="${x.id}"><option value="missing" ${x.status==='missing'?'selected':''}>Missing</option><option value="in_progress" ${x.status==='in_progress'?'selected':''}>In progress</option><option value="complete" ${x.status==='complete'?'selected':''}>Complete</option><option value="accepted" ${x.status==='accepted'?'selected':''}>Accepted</option></select></td></tr>`).join('')}</tbody></table></div>`,true);$$('[data-toi]').forEach(s=>s.onchange=async()=>{try{await api(`/api/turnover-items/${s.dataset.toi}`,{method:'PATCH',body:JSON.stringify({status:s.value})});toast('Turnover gate updated');await loadAll()}catch(err){toast(err.message)}})}catch(err){toast(err.message)}}

window.addEventListener('online',()=>{updateQueueBadge();toast('Connection restored — synchronising queued field updates');flushQueue()});window.addEventListener('offline',()=>{updateQueueBadge();toast('Offline field mode — updates will queue and sync automatically')});
boot();
setTimeout(()=>flushQueue(),1200);
