const encoder = new TextEncoder();
const json = (data, status = 200, headers = {}) => new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...headers } });
const now = () => new Date().toISOString();
const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;
const toB64 = (bytes) => btoa(String.fromCharCode(...bytes));
const fromB64 = (s) => Uint8Array.from(atob(s), c => c.charCodeAt(0));
const clean = (v, n = 500) => String(v ?? '').trim().slice(0, n);
const nullable = (v, n = 500) => clean(v, n) || null;

async function sha256(value) {
  const digest = await crypto.subtle.digest('SHA-256', typeof value === 'string' ? encoder.encode(value) : value);
  return toB64(new Uint8Array(digest));
}
async function hashPassword(password, salt = crypto.getRandomValues(new Uint8Array(16))) {
  const key = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt, iterations: 240000, hash: 'SHA-256' }, key, 256);
  return { salt: toB64(salt), hash: toB64(new Uint8Array(bits)) };
}
async function verifyPassword(password, saltB64, expectedB64) {
  const got = await hashPassword(password, fromB64(saltB64));
  const a = fromB64(got.hash), b = fromB64(expectedB64);
  return a.length === b.length && crypto.subtle.timingSafeEqual(a, b);
}
function getCookie(request, name) {
  const raw = request.headers.get('cookie') || '';
  for (const part of raw.split(';')) { const [k, ...v] = part.trim().split('='); if (k === name) return decodeURIComponent(v.join('=')); }
  return null;
}
async function currentUser(request, env) {
  const token = getCookie(request, 'qx_session'); if (!token) return null;
  return env.DB.prepare(`SELECT u.id,u.email,u.name,u.role,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1`).bind(await sha256(token), now()).first();
}
const roleAllowed = (u, roles) => u && u.active && roles.includes(u.role);
async function audit(env, userId, action, entityType, entityId, details = {}) {
  await env.DB.prepare(`INSERT INTO audit_log(id,user_id,action,entity_type,entity_id,details_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(id('audit'), userId || null, action, entityType, entityId || null, JSON.stringify(details), now()).run();
}
async function bodyJson(request) { try { return await request.json(); } catch { throw new Error('Invalid JSON body'); } }
function cookie(token, maxAge = 43200) { return `qx_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`; }
async function all(stmt) { const r = await stmt.all(); return r.results || []; }
async function refreshTurnover(env, packageId) {
  const r = await env.DB.prepare(`SELECT COUNT(*) total, SUM(CASE WHEN status='complete' OR status='accepted' THEN 1 ELSE 0 END) done FROM turnover_items WHERE package_id=? AND required=1`).bind(packageId).first();
  const total = Number(r?.total || 0), done = Number(r?.done || 0), pct = total ? Math.round(done * 100 / total) : 0;
  await env.DB.prepare(`UPDATE turnover_packages SET required_items=?,complete_items=?,readiness_percent=?,status=CASE WHEN ?=100 THEN 'ready' ELSE status END,updated_at=? WHERE id=?`).bind(total, done, pct, pct, now(), packageId).run();
}

async function handleApi(request, env, ctx) {
  const url = new URL(request.url), path = url.pathname, method = request.method;
  if (path === '/api/health') return json({ ok: true, app: env.APP_NAME, version: '4.0-market-leader', time: now() });
  if (path === '/api/setup/status' && method === 'GET') { const r = await env.DB.prepare('SELECT COUNT(*) count FROM users').first(); return json({ initialized: Number(r?.count || 0) > 0 }); }
  if (path === '/api/setup/bootstrap' && method === 'POST') {
    const c = await env.DB.prepare('SELECT COUNT(*) count FROM users').first(); if (Number(c?.count || 0) > 0) return json({ error: 'Already initialized' }, 409);
    if (!env.BOOTSTRAP_TOKEN) return json({ error: 'BOOTSTRAP_TOKEN is not configured' }, 503);
    const d = await bodyJson(request), supplied = encoder.encode(clean(d.token, 200)), expected = encoder.encode(String(env.BOOTSTRAP_TOKEN));
    if (supplied.length !== expected.length || !crypto.subtle.timingSafeEqual(supplied, expected)) return json({ error: 'Invalid bootstrap token' }, 403);
    if (!d.email || !d.name || String(d.password || '').length < 12) return json({ error: 'Name, email and password of at least 12 characters are required' }, 400);
    const pw = await hashPassword(String(d.password)), uid = id('usr');
    await env.DB.prepare(`INSERT INTO users(id,email,name,role,password_salt,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(uid, clean(d.email, 200).toLowerCase(), clean(d.name, 120), 'admin', pw.salt, pw.hash, 1, now(), now()).run();
    await audit(env, uid, 'bootstrap_admin', 'user', uid); return json({ ok: true }, 201);
  }
  if (path === '/api/auth/login' && method === 'POST') {
    const d = await bodyJson(request); const u = await env.DB.prepare('SELECT * FROM users WHERE email=? AND active=1 LIMIT 1').bind(clean(d.email, 200).toLowerCase()).first();
    if (!u || !(await verifyPassword(String(d.password || ''), u.password_salt, u.password_hash))) return json({ error: 'Invalid email or password' }, 401);
    const token = toB64(crypto.getRandomValues(new Uint8Array(32))).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''), expires = new Date(Date.now()+43200000).toISOString();
    await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)').bind(id('ses'), u.id, await sha256(token), expires, now()).run();
    ctx.waitUntil(audit(env, u.id, 'login', 'user', u.id)); return json({ user: { id:u.id,email:u.email,name:u.name,role:u.role } }, 200, { 'set-cookie': cookie(token) });
  }
  if (path === '/api/auth/logout' && method === 'POST') { const t = getCookie(request,'qx_session'); if(t) await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(t)).run(); return json({ok:true},200,{'set-cookie':'qx_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'}); }

  const user = await currentUser(request, env); if (!user) return json({ error:'Authentication required' },401);
  if (path === '/api/me' && method === 'GET') return json({ user });

  if (path === '/api/dashboard' && method === 'GET') {
    const projectId = url.searchParams.get('project_id'); const where = projectId ? ' WHERE project_id=?' : '';
    const bind = (sql) => projectId ? env.DB.prepare(sql + where).bind(projectId) : env.DB.prepare(sql + where);
    const [pr, eq, ins, def, pts, wit, turn] = await Promise.all([
      env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status IN ('active','witnessing','handover') THEN 1 ELSE 0 END) active FROM projects WHERE status!='archived'`).first(),
      bind(`SELECT COUNT(*) total,SUM(CASE WHEN status='complete' THEN 1 ELSE 0 END) complete,SUM(CASE WHEN status='blocked' THEN 1 ELSE 0 END) blocked FROM equipment`).first(),
      bind(`SELECT COUNT(*) total,SUM(CASE WHEN status='approved' THEN 1 ELSE 0 END) approved,SUM(CASE WHEN status='witness_required' THEN 1 ELSE 0 END) witness FROM inspections`).first(),
      bind(`SELECT COUNT(*) total,SUM(CASE WHEN status NOT IN ('closed','verified') THEN 1 ELSE 0 END) open,SUM(CASE WHEN category='A' AND status NOT IN ('closed','verified') THEN 1 ELSE 0 END) cat_a FROM defects`).first(),
      bind(`SELECT COUNT(*) total,SUM(CASE WHEN overall_status='pass' THEN 1 ELSE 0 END) passed,SUM(CASE WHEN overall_status='fail' THEN 1 ELSE 0 END) failed FROM bms_points`).first(),
      bind(`SELECT COUNT(*) total,SUM(CASE WHEN status='requested' THEN 1 ELSE 0 END) requested FROM witness_requests`).first(),
      bind(`SELECT COUNT(*) total,AVG(readiness_percent) avg_readiness,SUM(CASE WHEN status='ready' OR status='approved' THEN 1 ELSE 0 END) ready FROM turnover_packages`).first()
    ]);
    const recent = await all(env.DB.prepare(`SELECT a.*,u.name user_name FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 12`));
    return json({ projects:pr||{},equipment:eq||{},inspections:ins||{},defects:def||{},points:pts||{},witness:wit||{},turnover:turn||{},recent });
  }

  if (path === '/api/projects' && method === 'GET') {
    const rows = await all(env.DB.prepare(`SELECT p.*,
      (SELECT COUNT(*) FROM equipment e WHERE e.project_id=p.id) equipment_count,
      (SELECT COUNT(*) FROM defects d WHERE d.project_id=p.id AND d.status NOT IN ('closed','verified')) open_defects,
      (SELECT COUNT(*) FROM defects d WHERE d.project_id=p.id AND d.category='A' AND d.status NOT IN ('closed','verified')) cat_a,
      (SELECT COUNT(*) FROM systems s WHERE s.project_id=p.id) system_count,
      (SELECT ROUND(AVG(readiness_percent)) FROM turnover_packages t WHERE t.project_id=p.id) turnover_readiness
      FROM projects p ORDER BY p.updated_at DESC`)); return json({ projects:rows });
  }
  if (path === '/api/projects' && method === 'POST') {
    if(!roleAllowed(user,['admin','pm','engineer'])) return json({error:'Insufficient permission'},403); const d=await bodyJson(request); if(!d.code||!d.name) return json({error:'Project code and name are required'},400);
    const pid=id('prj'); await env.DB.prepare(`INSERT INTO projects(id,code,name,client,site_address,status,completion_target,project_type,commissioning_manager,practical_completion,created_by,created_at,updated_at) VALUES(?,?,?,?,?,'active',?,?,?,?,?,?,?)`).bind(pid,clean(d.code,60),clean(d.name,180),nullable(d.client,180),nullable(d.site_address,300),nullable(d.completion_target,30),clean(d.project_type||'commercial',40),nullable(d.commissioning_manager,120),nullable(d.practical_completion,30),user.id,now(),now()).run();
    ctx.waitUntil(audit(env,user.id,'create','project',pid,{code:d.code})); return json({id:pid},201);
  }

  if (path === '/api/systems' && method === 'GET') { const pid=url.searchParams.get('project_id'); const rows=await all(pid?env.DB.prepare(`SELECT s.*,(SELECT COUNT(*) FROM equipment e WHERE e.project_id=s.project_id AND (e.system=s.code OR e.system=s.name)) equipment_count,(SELECT COUNT(*) FROM defects d JOIN equipment e ON e.id=d.equipment_id WHERE e.project_id=s.project_id AND (e.system=s.code OR e.system=s.name) AND d.status NOT IN ('closed','verified')) open_defects FROM systems s WHERE s.project_id=? ORDER BY s.code`).bind(pid):env.DB.prepare('SELECT * FROM systems ORDER BY updated_at DESC LIMIT 500')); return json({systems:rows}); }
  if (path === '/api/systems' && method === 'POST') { if(!roleAllowed(user,['admin','pm','engineer'])) return json({error:'Insufficient permission'},403); const d=await bodyJson(request); if(!d.project_id||!d.code||!d.name)return json({error:'Project, system code and name are required'},400); const sid=id('sys'); await env.DB.prepare(`INSERT INTO systems(id,project_id,code,name,discipline,parent_system_id,location,status,target_date,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(sid,d.project_id,clean(d.code,80),clean(d.name,180),clean(d.discipline||'BMS',80),nullable(d.parent_system_id,80),nullable(d.location,180),clean(d.status||'construction',40),nullable(d.target_date,30),now(),now()).run(); ctx.waitUntil(audit(env,user.id,'create','system',sid)); return json({id:sid},201); }

  if (path === '/api/equipment' && method === 'GET') { const pid=url.searchParams.get('project_id'); const rows=await all(pid?env.DB.prepare(`SELECT e.*,(SELECT COUNT(*) FROM defects d WHERE d.equipment_id=e.id AND d.status NOT IN ('closed','verified')) open_defects,(SELECT COUNT(*) FROM inspections i WHERE i.equipment_id=e.id AND i.status='approved') approved_tests FROM equipment e WHERE e.project_id=? ORDER BY e.system,e.tag`).bind(pid):env.DB.prepare(`SELECT e.*,(SELECT COUNT(*) FROM defects d WHERE d.equipment_id=e.id AND d.status NOT IN ('closed','verified')) open_defects FROM equipment e ORDER BY e.updated_at DESC LIMIT 1000`)); return json({equipment:rows}); }
  if (path === '/api/equipment' && method === 'POST') { if(!roleAllowed(user,['admin','pm','engineer','site_manager','technician','electrician'])) return json({error:'Insufficient permission'},403); const d=await bodyJson(request); if(!d.project_id||!d.tag||!d.name)return json({error:'Project, tag and name are required'},400); const eid=id('eq'); await env.DB.prepare(`INSERT INTO equipment(id,project_id,tag,name,system,subsystem,building,level,area,equipment_type,manufacturer,model,serial_number,status,qr_code,install_status,qa_status,cx_status,turnover_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'not_started',?,'not_started','not_started','not_started','not_started',?,?)`).bind(eid,d.project_id,clean(d.tag,100),clean(d.name,180),nullable(d.system,120),nullable(d.subsystem,120),nullable(d.building,120),nullable(d.level,120),nullable(d.area,120),nullable(d.equipment_type,120),nullable(d.manufacturer,120),nullable(d.model,120),nullable(d.serial_number,120),eid,now(),now()).run(); ctx.waitUntil(audit(env,user.id,'create','equipment',eid,{tag:d.tag})); return json({id:eid,qr:`${url.origin}/?asset=${eid}`},201); }

  if (path === '/api/templates' && method === 'GET') { const rows=await all(env.DB.prepare(`SELECT t.*,(SELECT COUNT(*) FROM template_items ti WHERE ti.template_id=t.id) item_count,(SELECT COUNT(*) FROM template_items ti WHERE ti.template_id=t.id AND ti.hold_point=1) hold_points FROM templates t WHERE active=1 ORDER BY discipline,name`)); return json({templates:rows}); }

  if (path === '/api/inspections' && method === 'GET') { const pid=url.searchParams.get('project_id'); const q=`SELECT i.*,t.name template_name,t.discipline,t.stage,e.tag equipment_tag,e.name equipment_name,u.name assigned_name,(SELECT COUNT(*) FROM inspection_results r WHERE r.inspection_id=i.id AND r.result='fail') fails,(SELECT COUNT(*) FROM inspection_results r WHERE r.inspection_id=i.id AND r.result IS NOT NULL) answered,(SELECT COUNT(*) FROM inspection_results r WHERE r.inspection_id=i.id) total_lines FROM inspections i JOIN templates t ON t.id=i.template_id LEFT JOIN equipment e ON e.id=i.equipment_id LEFT JOIN users u ON u.id=i.assigned_to`; const rows=await all(pid?env.DB.prepare(q+' WHERE i.project_id=? ORDER BY i.updated_at DESC').bind(pid):env.DB.prepare(q+' ORDER BY i.updated_at DESC LIMIT 1000')); return json({inspections:rows}); }
  if (path === '/api/inspections' && method === 'POST') { const d=await bodyJson(request); if(!d.project_id||!d.template_id||!d.title)return json({error:'Project, template and title are required'},400); const iid=id('ins'); await env.DB.prepare(`INSERT INTO inspections(id,project_id,equipment_id,template_id,title,status,assigned_to,created_by,created_at,updated_at) VALUES(?,?,?,?,?,'in_progress',?,?,?,?)`).bind(iid,d.project_id,nullable(d.equipment_id,100),d.template_id,clean(d.title,220),nullable(d.assigned_to,100),user.id,now(),now()).run(); const items=await all(env.DB.prepare('SELECT id FROM template_items WHERE template_id=? ORDER BY sort_order').bind(d.template_id)); for(const item of items){ await env.DB.prepare(`INSERT INTO inspection_results(id,inspection_id,template_item_id) VALUES(?,?,?)`).bind(id('res'),iid,item.id).run(); } ctx.waitUntil(audit(env,user.id,'create','inspection',iid)); return json({id:iid},201); }
  const insMatch=path.match(/^\/api\/inspections\/([^/]+)$/); if(insMatch&&method==='GET'){ const iid=insMatch[1]; const inspection=await env.DB.prepare(`SELECT i.*,t.name template_name,t.stage,t.discipline,e.tag equipment_tag,e.name equipment_name FROM inspections i JOIN templates t ON t.id=i.template_id LEFT JOIN equipment e ON e.id=i.equipment_id WHERE i.id=?`).bind(iid).first(); if(!inspection)return json({error:'Not found'},404); const results=await all(env.DB.prepare(`SELECT r.*,ti.section,ti.item_text,ti.response_type,ti.mandatory,ti.hold_point,u.name completed_by_name FROM inspection_results r JOIN template_items ti ON ti.id=r.template_item_id LEFT JOIN users u ON u.id=r.completed_by WHERE r.inspection_id=? ORDER BY ti.sort_order`).bind(iid)); return json({inspection,results}); }
  const resMatch=path.match(/^\/api\/inspection-results\/([^/]+)$/); if(resMatch&&method==='PATCH'){ const d=await bodyJson(request); const rid=resMatch[1]; const existing=await env.DB.prepare(`SELECT r.*,i.project_id,i.equipment_id,i.id inspection_id,ti.item_text,ti.hold_point FROM inspection_results r JOIN inspections i ON i.id=r.inspection_id JOIN template_items ti ON ti.id=r.template_item_id WHERE r.id=?`).bind(rid).first(); if(!existing)return json({error:'Not found'},404); const result=['pass','fail','na',null].includes(d.result)?d.result:null; await env.DB.prepare(`UPDATE inspection_results SET result=?,value_text=?,comment=?,completed_by=?,completed_at=? WHERE id=?`).bind(result,nullable(d.value_text,500),nullable(d.comment,1200),user.id,now(),rid).run(); if(result==='fail'){ const exists=await env.DB.prepare(`SELECT id FROM defects WHERE inspection_id=? AND title=? AND status NOT IN ('closed','verified') LIMIT 1`).bind(existing.inspection_id,`Failed check: ${existing.item_text}`).first(); if(!exists){ const did=id('def'); await env.DB.prepare(`INSERT INTO defects(id,project_id,equipment_id,inspection_id,title,description,discipline,severity,category,status,source,raised_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'high','A','open','inspection',?,?,?,?)`).bind(did,existing.project_id,existing.equipment_id,existing.inspection_id,`Failed check: ${existing.item_text}`,nullable(d.comment,1200),'QA',user.id,now(),now()).run(); } } const counts=await env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN result IS NOT NULL THEN 1 ELSE 0 END) answered,SUM(CASE WHEN result='fail' THEN 1 ELSE 0 END) fails FROM inspection_results WHERE inspection_id=?`).bind(existing.inspection_id).first(); const status=Number(counts?.answered||0)===Number(counts?.total||0)?(Number(counts?.fails||0)>0?'submitted':'witness_required'):'in_progress'; await env.DB.prepare('UPDATE inspections SET status=?,updated_at=? WHERE id=?').bind(status,now(),existing.inspection_id).run(); ctx.waitUntil(audit(env,user.id,'update_result','inspection_result',rid,{result})); return json({ok:true,status}); }

  if (path === '/api/defects' && method === 'GET') { const pid=url.searchParams.get('project_id'); const q=`SELECT d.*,e.tag equipment_tag,e.name equipment_name,u.name assigned_name,r.name raised_name FROM defects d LEFT JOIN equipment e ON e.id=d.equipment_id LEFT JOIN users u ON u.id=d.assigned_to LEFT JOIN users r ON r.id=d.raised_by`; const rows=await all(pid?env.DB.prepare(q+' WHERE d.project_id=? ORDER BY CASE d.category WHEN \'A\' THEN 1 WHEN \'B\' THEN 2 ELSE 3 END,d.updated_at DESC').bind(pid):env.DB.prepare(q+' ORDER BY d.updated_at DESC LIMIT 1000')); return json({defects:rows}); }
  if (path === '/api/defects' && method === 'POST') { const d=await bodyJson(request); if(!d.project_id||!d.title)return json({error:'Project and title are required'},400); const did=id('def'); await env.DB.prepare(`INSERT INTO defects(id,project_id,equipment_id,inspection_id,title,description,discipline,severity,category,status,assigned_to,due_date,source,raised_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'open',?,?,?, ?,?,?)`).bind(did,d.project_id,nullable(d.equipment_id,100),nullable(d.inspection_id,100),clean(d.title,220),nullable(d.description,2000),clean(d.discipline||'general',80),clean(d.severity||'medium',20),clean(d.category||'B',1),nullable(d.assigned_to,100),nullable(d.due_date,30),clean(d.source||'field',40),user.id,now(),now()).run(); ctx.waitUntil(audit(env,user.id,'create','defect',did)); return json({id:did},201); }
  const defMatch=path.match(/^\/api\/defects\/([^/]+)$/); if(defMatch&&method==='PATCH'){ const d=await bodyJson(request), did=defMatch[1]; const status=clean(d.status||'open',30); await env.DB.prepare(`UPDATE defects SET status=?,rectification_note=COALESCE(?,rectification_note),verified_by=CASE WHEN ? IN ('verified','closed') THEN ? ELSE verified_by END,verified_at=CASE WHEN ? IN ('verified','closed') THEN ? ELSE verified_at END,updated_at=? WHERE id=?`).bind(status,nullable(d.rectification_note,2000),status,user.id,status,now(),now(),did).run(); ctx.waitUntil(audit(env,user.id,'update','defect',did,{status})); return json({ok:true}); }

  if (path === '/api/bms-points' && method === 'GET') { const pid=url.searchParams.get('project_id'); const rows=await all(pid?env.DB.prepare(`SELECT p.*,e.tag equipment_tag FROM bms_points p LEFT JOIN equipment e ON e.id=p.equipment_id WHERE p.project_id=? ORDER BY p.controller,p.point_name LIMIT 5000`).bind(pid):env.DB.prepare(`SELECT p.*,e.tag equipment_tag FROM bms_points p LEFT JOIN equipment e ON e.id=p.equipment_id ORDER BY p.updated_at DESC LIMIT 2000`)); return json({points:rows}); }
  if (path === '/api/bms-points/import' && method === 'POST') { if(!roleAllowed(user,['admin','pm','engineer','technician']))return json({error:'Insufficient permission'},403); const d=await bodyJson(request); if(!d.project_id||!Array.isArray(d.points))return json({error:'project_id and points array required'},400); let created=0; for(const p of d.points.slice(0,5000)){ if(!p.point_name||!p.point_type)continue; await env.DB.prepare(`INSERT INTO bms_points(id,project_id,equipment_id,system_id,controller,point_name,point_type,io_address,cable_number,terminal,field_device,engineering_units,normal_state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id('pt'),d.project_id,nullable(p.equipment_id,100),nullable(p.system_id,100),nullable(p.controller,120),clean(p.point_name,180),clean(p.point_type,20).toUpperCase(),nullable(p.io_address,80),nullable(p.cable_number,80),nullable(p.terminal,80),nullable(p.field_device,160),nullable(p.engineering_units,50),nullable(p.normal_state,80),now(),now()).run(); created++; } ctx.waitUntil(audit(env,user.id,'bulk_import','bms_point',d.project_id,{created})); return json({created},201); }
  const ptMatch=path.match(/^\/api\/bms-points\/([^/]+)$/); if(ptMatch&&method==='PATCH'){ const d=await bodyJson(request), pid=ptMatch[1]; const vals=['pass','fail','na','not_tested']; const fs=vals.includes(d.field_status)?d.field_status:'not_tested', cs=vals.includes(d.controller_status)?d.controller_status:'not_tested', gs=vals.includes(d.graphics_status)?d.graphics_status:'not_tested', as=vals.includes(d.alarm_status)?d.alarm_status:'not_tested'; const statuses=[fs,cs,gs,as].filter(x=>x!=='na'); const overall=statuses.includes('fail')?'fail':(statuses.length&&statuses.every(x=>x==='pass')?'pass':'not_tested'); await env.DB.prepare(`UPDATE bms_points SET field_status=?,controller_status=?,graphics_status=?,alarm_status=?,overall_status=?,comment=?,tested_by=?,tested_at=?,updated_at=? WHERE id=?`).bind(fs,cs,gs,as,overall,nullable(d.comment,1000),user.id,now(),now(),pid).run(); return json({ok:true,overall}); }

  if (path === '/api/turnover' && method === 'GET') { const pid=url.searchParams.get('project_id'); const rows=await all(pid?env.DB.prepare(`SELECT t.*,s.code system_code,s.name system_name FROM turnover_packages t LEFT JOIN systems s ON s.id=t.system_id WHERE t.project_id=? ORDER BY t.readiness_percent,s.code`).bind(pid):env.DB.prepare(`SELECT t.*,s.code system_code,s.name system_name FROM turnover_packages t LEFT JOIN systems s ON s.id=t.system_id ORDER BY t.updated_at DESC LIMIT 500`)); return json({packages:rows}); }
  if (path === '/api/turnover' && method === 'POST') { const d=await bodyJson(request); if(!d.project_id||!d.name)return json({error:'Project and package name required'},400); const tid=id('top'); await env.DB.prepare(`INSERT INTO turnover_packages(id,project_id,system_id,name,status,readiness_percent,required_items,complete_items,created_at,updated_at) VALUES(?,?,?,?,'draft',0,0,0,?,?)`).bind(tid,d.project_id,nullable(d.system_id,100),clean(d.name,200),now(),now()).run(); const defaults=['Approved as-built drawings','Equipment/tag register complete','QA/ITR records complete','Electrical test records complete','BMS I/O checkout complete','Functional tests approved','Witness tests signed','Category A defects closed','Category B defects accepted','O&M manuals available','Controller/software backups archived','Training/operations handover complete']; let i=0; for(const name of defaults){ await env.DB.prepare(`INSERT INTO turnover_items(id,package_id,category,name,required,status,updated_at) VALUES(?,?,?, ?,1,'missing',?)`).bind(id('toi'),tid,i<2?'Drawings':i<7?'Testing':i<9?'Defects':'Handover',name,now()).run(); i++; } await refreshTurnover(env,tid); return json({id:tid},201); }
  const topMatch=path.match(/^\/api\/turnover\/([^/]+)$/); if(topMatch&&method==='GET'){ const pack=await env.DB.prepare(`SELECT t.*,s.code system_code,s.name system_name FROM turnover_packages t LEFT JOIN systems s ON s.id=t.system_id WHERE t.id=?`).bind(topMatch[1]).first(); if(!pack)return json({error:'Not found'},404); const items=await all(env.DB.prepare(`SELECT * FROM turnover_items WHERE package_id=? ORDER BY category,name`).bind(topMatch[1])); return json({package:pack,items}); }
  const toiMatch=path.match(/^\/api\/turnover-items\/([^/]+)$/); if(toiMatch&&method==='PATCH'){ const d=await bodyJson(request), iid=toiMatch[1]; const row=await env.DB.prepare('SELECT package_id FROM turnover_items WHERE id=?').bind(iid).first(); if(!row)return json({error:'Not found'},404); await env.DB.prepare(`UPDATE turnover_items SET status=?,note=?,updated_by=?,updated_at=? WHERE id=?`).bind(clean(d.status||'missing',30),nullable(d.note,1200),user.id,now(),iid).run(); await refreshTurnover(env,row.package_id); return json({ok:true}); }

  if (path === '/api/witness' && method === 'GET') { const pid=url.searchParams.get('project_id'); const rows=await all(pid?env.DB.prepare(`SELECT w.*,i.title inspection_title,s.code system_code FROM witness_requests w LEFT JOIN inspections i ON i.id=w.inspection_id LEFT JOIN systems s ON s.id=w.system_id WHERE w.project_id=? ORDER BY w.requested_for`).bind(pid):env.DB.prepare(`SELECT w.*,i.title inspection_title,s.code system_code FROM witness_requests w LEFT JOIN inspections i ON i.id=w.inspection_id LEFT JOIN systems s ON s.id=w.system_id ORDER BY w.updated_at DESC LIMIT 500`)); return json({witness:rows}); }
  if (path === '/api/witness' && method === 'POST') { const d=await bodyJson(request); if(!d.project_id||!d.requested_for)return json({error:'Project and requested date/time required'},400); const wid=id('wit'); await env.DB.prepare(`INSERT INTO witness_requests(id,project_id,inspection_id,system_id,requested_for,witness_party,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,'requested',?,?,?)`).bind(wid,d.project_id,nullable(d.inspection_id,100),nullable(d.system_id,100),clean(d.requested_for,40),nullable(d.witness_party,180),user.id,now(),now()).run(); return json({id:wid},201); }

  if (path === '/api/users' && method === 'GET') { const rows=await all(env.DB.prepare(`SELECT id,email,name,role,active,created_at FROM users ORDER BY name`)); return json({users:rows}); }
  if (path === '/api/users' && method === 'POST') { if(!roleAllowed(user,['admin']))return json({error:'Admin only'},403); const d=await bodyJson(request); if(!d.email||!d.name||String(d.password||'').length<12)return json({error:'Name, email and 12+ character password required'},400); const pw=await hashPassword(String(d.password)), uid=id('usr'); await env.DB.prepare(`INSERT INTO users(id,email,name,role,password_salt,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)`).bind(uid,clean(d.email,200).toLowerCase(),clean(d.name,120),clean(d.role||'technician',30),pw.salt,pw.hash,now(),now()).run(); return json({id:uid},201); }

  if (path === '/api/files' && method === 'POST') { const projectId=url.searchParams.get('project_id'); if(!projectId)return json({error:'project_id required'},400); const fileName=clean(request.headers.get('x-file-name')||'evidence.bin',240), contentType=request.headers.get('content-type')||'application/octet-stream'; if(request.body===null)return json({error:'File body required'},400); const key=`${projectId}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${fileName.replace(/[^a-zA-Z0-9._-]/g,'_')}`; const obj=await env.FILES.put(key,request.body,{httpMetadata:{contentType},customMetadata:{uploadedBy:user.id}}); const fid=id('file'); await env.DB.prepare(`INSERT INTO files(id,project_id,equipment_id,inspection_id,defect_id,object_key,file_name,content_type,size_bytes,uploaded_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(fid,projectId,nullable(url.searchParams.get('equipment_id'),100),nullable(url.searchParams.get('inspection_id'),100),nullable(url.searchParams.get('defect_id'),100),key,fileName,contentType,Number(obj?.size||0),user.id,now()).run(); return json({id:fid,file_name:fileName},201); }
  const fileMatch=path.match(/^\/api\/files\/([^/]+)$/); if(fileMatch&&method==='GET'){ const f=await env.DB.prepare('SELECT * FROM files WHERE id=?').bind(fileMatch[1]).first(); if(!f)return json({error:'Not found'},404); const o=await env.FILES.get(f.object_key); if(!o)return json({error:'Object missing'},404); const h=new Headers(); o.writeHttpMetadata(h); h.set('etag',o.httpEtag); h.set('content-disposition',`inline; filename="${f.file_name.replaceAll('"','')}"`); return new Response(o.body,{headers:h}); }

  if (path === '/api/readiness' && method === 'GET') {
    const pid=url.searchParams.get('project_id'); if(!pid)return json({error:'project_id required'},400);
    const [eq,ins,defs,pts,wit,turn] = await Promise.all([
      env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='complete' THEN 1 ELSE 0 END) complete FROM equipment WHERE project_id=?`).bind(pid).first(),
      env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status IN ('approved','complete') THEN 1 ELSE 0 END) complete,SUM(CASE WHEN status IN ('submitted','witness_required') THEN 1 ELSE 0 END) pending FROM inspections WHERE project_id=?`).bind(pid).first(),
      env.DB.prepare(`SELECT SUM(CASE WHEN status NOT IN ('closed','verified') THEN 1 ELSE 0 END) open,SUM(CASE WHEN category='A' AND status NOT IN ('closed','verified') THEN 1 ELSE 0 END) cat_a FROM defects WHERE project_id=?`).bind(pid).first(),
      env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN overall_status='pass' THEN 1 ELSE 0 END) passed,SUM(CASE WHEN overall_status='fail' THEN 1 ELSE 0 END) failed FROM bms_points WHERE project_id=?`).bind(pid).first(),
      env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status IN ('completed','accepted','passed') THEN 1 ELSE 0 END) complete,SUM(CASE WHEN status='requested' THEN 1 ELSE 0 END) pending FROM witness_requests WHERE project_id=?`).bind(pid).first(),
      env.DB.prepare(`SELECT COUNT(*) total,AVG(readiness_percent) avg_readiness,SUM(CASE WHEN readiness_percent=100 THEN 1 ELSE 0 END) ready FROM turnover_packages WHERE project_id=?`).bind(pid).first()
    ]);
    const blockers=[]; let earned=0,totalWeight=100;
    if(Number(defs?.cat_a||0)===0) earned+=20; else blockers.push({code:'NO_CAT_A',severity:'critical',label:`${defs.cat_a} Category A defect(s) open`,route:'defects'});
    if(Number(ins?.total||0)>0 && Number(ins?.complete||0)===Number(ins?.total||0)) earned+=20; else blockers.push({code:'TESTS_COMPLETE',severity:'high',label:`${Math.max(0,Number(ins?.total||0)-Number(ins?.complete||0))} test(s) not approved`,route:'inspections'});
    if(Number(pts?.total||0)===0 || (Number(pts?.failed||0)===0 && Number(pts?.passed||0)===Number(pts?.total||0))) earned+=20; else blockers.push({code:'BMS_PROVEN',severity:Number(pts?.failed||0)?'critical':'high',label:`${pts.failed||0} failed / ${Math.max(0,Number(pts?.total||0)-Number(pts?.passed||0))} unproven BMS point(s)`,route:'points'});
    if(Number(wit?.pending||0)===0) earned+=15; else blockers.push({code:'WITNESS_CLEAR',severity:'high',label:`${wit.pending} witness request(s) pending`,route:'witness'});
    if(Number(turn?.total||0)>0 && Number(turn?.ready||0)===Number(turn?.total||0)) earned+=15; else blockers.push({code:'TURNOVER_READY',severity:'medium',label:`Turnover readiness ${Math.round(Number(turn?.avg_readiness||0))}%`,route:'turnover'});
    const eqPct=Number(eq?.total||0)?Math.round(Number(eq?.complete||0)*100/Number(eq.total)):100; earned += Math.round(10*eqPct/100);
    const score=Math.min(100,Math.round(earned)); const metrics={equipment:eq||{},inspections:ins||{},defects:defs||{},points:pts||{},witness:wit||{},turnover:turn||{},equipment_percent:eqPct};
    if(url.searchParams.get('snapshot')==='1'){await env.DB.prepare(`INSERT INTO readiness_snapshots(id,project_id,score,blocker_count,blockers_json,metrics_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(id('rdy'),pid,score,blockers.length,JSON.stringify(blockers),JSON.stringify(metrics),now()).run();}
    return json({score,grade:score>=95?'READY':score>=80?'NEAR READY':score>=60?'AT RISK':'BLOCKED',blockers,metrics});
  }

  if (path === '/api/actions' && method === 'GET') { const pid=url.searchParams.get('project_id'); const rows=await all(pid?env.DB.prepare(`SELECT a.*,u.name assigned_name FROM action_items a LEFT JOIN users u ON u.id=a.assigned_to WHERE a.project_id=? ORDER BY CASE a.priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'normal' THEN 3 ELSE 4 END,a.due_at`).bind(pid):env.DB.prepare(`SELECT a.*,u.name assigned_name FROM action_items a LEFT JOIN users u ON u.id=a.assigned_to ORDER BY a.updated_at DESC LIMIT 500`)); return json({actions:rows}); }
  if (path === '/api/actions' && method === 'POST') { const d=await bodyJson(request); if(!d.project_id||!d.title)return json({error:'Project and title required'},400); const aid=id('act'); await env.DB.prepare(`INSERT INTO action_items(id,project_id,system_id,equipment_id,title,description,priority,status,assigned_to,due_at,source,source_id,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'open',?,?,?,?,?,?,?)`).bind(aid,d.project_id,nullable(d.system_id,100),nullable(d.equipment_id,100),clean(d.title,220),nullable(d.description,2000),clean(d.priority||'normal',20),nullable(d.assigned_to,100),nullable(d.due_at,40),clean(d.source||'manual',40),nullable(d.source_id,100),user.id,now(),now()).run(); return json({id:aid},201); }
  const actionMatch=path.match(/^\/api\/actions\/([^/]+)$/); if(actionMatch&&method==='PATCH'){const d=await bodyJson(request);await env.DB.prepare(`UPDATE action_items SET status=COALESCE(?,status),priority=COALESCE(?,priority),assigned_to=COALESCE(?,assigned_to),due_at=COALESCE(?,due_at),updated_at=? WHERE id=?`).bind(nullable(d.status,30),nullable(d.priority,20),nullable(d.assigned_to,100),nullable(d.due_at,40),now(),actionMatch[1]).run();return json({ok:true});}

  if (path === '/api/signoffs' && method === 'GET') { const pid=url.searchParams.get('project_id'); const rows=await all(pid?env.DB.prepare(`SELECT * FROM signoffs WHERE project_id=? ORDER BY signed_at DESC`).bind(pid):env.DB.prepare(`SELECT * FROM signoffs ORDER BY signed_at DESC LIMIT 500`)); return json({signoffs:rows}); }
  if (path === '/api/signoffs' && method === 'POST') { const d=await bodyJson(request); if(!d.project_id||!d.entity_type||!d.entity_id||!d.signer_name)return json({error:'Project, entity and signer required'},400); const sid=id('sig'); await env.DB.prepare(`INSERT INTO signoffs(id,project_id,entity_type,entity_id,signoff_type,signer_name,signer_company,signer_role,signature_data,declaration,signed_at,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(sid,d.project_id,clean(d.entity_type,40),clean(d.entity_id,100),clean(d.signoff_type||'acceptance',40),clean(d.signer_name,160),nullable(d.signer_company,160),nullable(d.signer_role,120),nullable(d.signature_data,100000),nullable(d.declaration,1200),now(),user.id,now()).run();ctx.waitUntil(audit(env,user.id,'signoff',d.entity_type,d.entity_id,{signer:d.signer_name,type:d.signoff_type}));return json({id:sid,signed_at:now()},201); }

  if (path === '/api/ai/project-builder' && method === 'POST') { const d=await bodyJson(request); if(!d.project_id||!d.source_text)return json({error:'Project and source text required'},400); const text=clean(d.source_text,50000); const tags=[...text.matchAll(/\b(?:AHU|FCU|MSSB|MCC|VSD|PUMP|FAN|CHW|HHW|BMS|JACE|DDC|UPS)[-_ ]?\d{1,4}[A-Z]?\b/gi)].map(m=>m[0].toUpperCase().replace(/\s+/g,'-')); const unique=[...new Set(tags)].slice(0,500); const proposal={equipment:unique.map(tag=>({tag,name:tag,equipment_type:tag.split(/[-_]/)[0]})),suggested_templates:['Cable & Termination QA','BMS Point-to-Point / I/O Checkout','MSSB/MCC Pre-Energisation QA','Functional Performance Test'],notes:'Machine-assisted proposal only. Review against approved drawings, specifications and sequence before applying.'}; const jid=id('aij'); await env.DB.prepare(`INSERT INTO ai_jobs(id,project_id,job_type,status,source_text,proposal_json,created_by,created_at,updated_at) VALUES(?,?,'project_builder','proposed',?,?,?,?,?)`).bind(jid,d.project_id,text,JSON.stringify(proposal),user.id,now(),now()).run(); return json({id:jid,proposal},201); }

  if (path === '/api/sync/batch' && method === 'POST') { const d=await bodyJson(request); if(!Array.isArray(d.operations))return json({error:'operations array required'},400); const results=[]; for(const op of d.operations.slice(0,250)){const key=clean(op.operation_key,120);if(!key){results.push({ok:false,error:'missing operation_key'});continue;}const existing=await env.DB.prepare('SELECT id FROM sync_operations WHERE operation_key=?').bind(key).first();if(existing){results.push({ok:true,duplicate:true,operation_key:key});continue;}await env.DB.prepare(`INSERT INTO sync_operations(id,user_id,device_id,operation_key,entity_type,entity_id,operation,payload_json,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id('syn'),user.id,nullable(d.device_id,120),key,clean(op.entity_type||'unknown',50),nullable(op.entity_id,100),clean(op.operation||'update',30),JSON.stringify(op.payload||{}),'received',now()).run();results.push({ok:true,operation_key:key,accepted:true});}return json({results}); }

  return json({ error:'API route not found' },404);
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    try {
      if (url.pathname.startsWith('/api/')) return await handleApi(request, env, ctx);
      return await env.ASSETS.fetch(request);
    } catch (error) {
      console.error(JSON.stringify({level:'error',message:error?.message||String(error),path:url.pathname}));
      return url.pathname.startsWith('/api/') ? json({error:'Server error',detail:env.ENVIRONMENT==='development'?String(error?.message||error):undefined},500) : new Response('Application error',{status:500});
    }
  }
};
